<%@ Page Title="" Language="C#" MasterPageFile="~/Site.Master" AutoEventWireup="true" CodeBehind="Gallery.aspx.cs" Inherits="WebApplication1.Gallery" %>
<asp:Content ID="Content1" ContentPlaceHolderID="MainContent" runat="server">
    <p style="height: 2547px" class="text-left">
        <strong>
        <asp:Label ID="lblCCrow" runat="server" style="z-index: 1; position: absolute; top: 440px; left: 505px; text-decoration: underline;" Text="Carrion Crow"></asp:Label>
        </strong>
        <asp:Label ID="lblMagpieSpec" runat="server" style="z-index: 1; position: absolute; top: 1215px; left: 275px; width: 345px;" Text="Length: 44-46 cm  (18&quot) Wing Span: 52-60 cm  (20-24&quot) Weight: 200-250 g  (7-9 oz) Present: All Year"></asp:Label>
        <br />
        <asp:Image ID="imgBlackbird" runat="server" ImageUrl="~/Media Content/Gallery Images/Blackbird.jpg" style="left: 25px; top: 290px; bottom: 125px; width: 145px; height: 125px;" />
        <asp:Image ID="imgCCrow" runat="server" ImageUrl="~/Media Content/Gallery Images/Carrion Crow.jpg" style="left: 655px; top: 455px; bottom: 128px; z-index: 1; position: absolute; width: 144px; height: 125px;" />
        <asp:Image ID="imgCommonGull" runat="server" ImageUrl="~/Media Content/Gallery Images/Common Gull.jpg" style="left: 60px; top: 640px; bottom: 342px; width: 145px; height: 125px; right: 619px;" />
        <asp:Image ID="imgJackdaw" runat="server" ImageUrl="~/Media Content/Gallery Images/Jackdaw.jpg" style="left: 60px; top: 1010px; bottom: 262px; width: 145px; height: 125px;" />
        <asp:Image ID="imgMagpie" runat="server" ImageUrl="~/Media Content/Gallery Images/Magpie.jpg" style="left: 635px; top: 1190px; bottom: 139px; width: 144px; height: 125px;" />
        <asp:Image ID="imgPheasant" runat="server" ImageUrl="~/Media Content/Gallery Images/Pheasant.jpg" style="left: 45px; top: 1375px; bottom: 153px; width: 144px; height: 125px;" />
        <asp:Image ID="imgPigeon" runat="server" ImageUrl="~/Media Content/Gallery Images/Pigeon.jpg" style="left: 645px; top: 1550px; bottom: 292px; width: 144px; height: 125px;" />
        <asp:Image ID="imgRaven" runat="server" ImageUrl="~/Media Content/Gallery Images/Raven.jpg" style="left: 50px; top: 1735px; bottom: 278px; width: 145px; height: 125px;" />
        <asp:Image ID="imgRobin" runat="server" ImageUrl="~/Media Content/Gallery Images/Robin.jpg" style="left: 640px; top: 1920px; bottom: 202px; width: 144px; height: 125px;" />
        <asp:Image ID="imgSwallow" runat="server" ImageUrl="~/Media Content/Gallery Images/Swallow.jpg" style="left: 630px; top: 2320px; bottom: 258px; height: 125px; width: 145px;" />
        <asp:Image ID="imgRook" runat="server" ImageUrl="~/Media Content/Gallery Images/Rook.jpg" style="left: 55px; top: 2140px; bottom: 227px; width: 145px; height: 125px;" />
        <strong>
        <asp:Label ID="lblBlackbird" runat="server" style="z-index: 1; position: absolute; top: 255px; left: 235px; font-family: Arial; font-size: medium; text-decoration: underline;" Text="Blackbird"></asp:Label>
        <asp:Label ID="lblCommonGull" runat="server" style="z-index: 1; position: absolute; top: 635px; left: 245px; text-decoration: underline;" Text="Common Gull"></asp:Label>
        <asp:Label ID="lblCuckoo" runat="server" style="z-index: 1; position: absolute; top: 810px; left: 510px; height: 20px; text-decoration: underline; width: 63px;" Text="Cuckoo"></asp:Label>
        <asp:Label ID="lblJackdaw" runat="server" style="z-index: 1; position: absolute; top: 1000px; left: 240px; text-decoration: underline;" Text="Jackdaw"></asp:Label>
        <asp:Label ID="lblMagpie" runat="server" style="z-index: 1; position: absolute; top: 1175px; left: 560px; text-decoration: underline;" Text="Magpie"></asp:Label>
        <asp:Label ID="lblPheasant" runat="server" style="z-index: 1; position: absolute; top: 1370px; left: 220px; text-decoration: underline;" Text="Pheasant"></asp:Label>
        <asp:Label ID="lblPigeon" runat="server" style="z-index: 1; position: absolute; top: 1540px; left: 565px; text-decoration: underline;" Text="Pigeon"></asp:Label>
        <asp:Label ID="lblRaven" runat="server" style="z-index: 1; position: absolute; top: 1730px; left: 225px; text-decoration: underline;" Text="Raven"></asp:Label>
        <asp:Label ID="lblRobin" runat="server" style="z-index: 1; position: absolute; top: 1910px; left: 550px; width: 45px; height: 20px; text-decoration: underline;" Text="Robin"></asp:Label>
        <asp:Label ID="lblRook" runat="server" style="z-index: 1; position: absolute; top: 2130px; left: 235px; text-decoration: underline;" Text="Rook"></asp:Label>
        <asp:Label ID="lblSwallow" runat="server" style="z-index: 1; position: absolute; top: 2310px; left: 530px; height: 20px; text-decoration: underline;" Text="Swallow"></asp:Label>
        </strong>
        <asp:Label ID="lblBlackbirdSpec" runat="server" style="z-index: 1; position: absolute; top: 295px; left: 200px; height: 55px; width: 360px" Text="Length: 24-25 cm  (10&quot;)  Wing Span: 35-38 cm  (14-15&quot;) Weight: 80-125 g  (3-4½ oz)  Present: All Year"></asp:Label>
        <asp:Label ID="lblCCrowSpec" runat="server" style="z-index: 1; position: absolute; top: 475px; left: 265px; width: 375px;" Text="Length: 45-47 cm  (18-19&quot) Wing Span: 93-104 cm  (37-42&quot) Weight: 370-650 g  (¾-1½) Present: All Year"></asp:Label>
        <asp:Label ID="lblBlackbirdDescription" runat="server" style="z-index: 1; position: absolute; top: 355px; left: 190px; height: 60px; width: 565px;" Text="The Blackbird sings from a perch and its song is rich, varied and flute-like, but usually finishes in a squeaky phrase. Their calls are loud and varied. The warning call is given with flicking wings and tail and sounds a little like chook, and the alarm call is a loud rattle."></asp:Label>
        <asp:Label ID="Label2" runat="server" style="z-index: 1; position: absolute; top: 530px; left: 65px; width: 575px;" Text="In flight, the Carrion Crow has a shorter head than the Rook, as well as having slower wing beats. The tail is squarer in the Carrion Crow, and the fingers at the wing tips are less splayed. The Carrion Crow has many calls but the most common is kraa-kraa-kraa."></asp:Label>
        <asp:Label ID="lblCommonGullSpec" runat="server" style="z-index: 1; position: absolute; top: 675px; left: 230px; width: 390px;" Text="Length: 38-44 cm  (15-18&quot) Wing Span: 106-125 cm  (42-50&quot) Weight: 300-500 g  (11-18 oz) Present: All Year "></asp:Label>
        <asp:Label ID="lblCommonGullDescript" runat="server" style="z-index: 1; position: absolute; top: 735px; left: 225px; width: 570px;" Text="The Common Gull is larger than the Black-headed Gull, but smaller than the Herring Gull. Their calls are high pitched, some are laughing calls and others are mewing calls: keow. "></asp:Label>
        <asp:Image ID="imgCuckoo" runat="server" ImageUrl="~/Media Content/Gallery Images/Cuckoo.jpg" style="left: 630px; top: 820px; bottom: 105px; width: 144px; height: 125px;" />
        <asp:Label ID="lblCuckooSpec" runat="server" style="z-index: 1; position: absolute; top: 850px; left: 230px; width: 395px; height: 80px" Text="Length: 32-36 cm  (13-14½&quot) Wing Span: 54-60 cm  (21½-24&quot) Weight: 105-130 g  (3¾-4¾ oz) Present: Summer"></asp:Label>
        <asp:Label ID="lblCuckooDescript" runat="server" style="z-index: 1; position: absolute; top: 910px; left: 70px; width: 535px;" Text="The female has a rich bubbling chuckle, but the male's call is the very familiar cuckoo. Generally, if you hear a Cuckoo singing you will probably not see it until it stops singing, which is when it flies away from its song post."></asp:Label>
        <asp:Label ID="lblJackdawSpec" runat="server" style="z-index: 1; position: absolute; top: 1035px; left: 230px; width: 325px;" Text="Length: 33 cm  (13&quot) Wing Span: 67-74 cm  (27-30&quot) Weight: 220-270 g  (8-9 oz) Present: All Year"></asp:Label>
        <asp:Label ID="lblDescript" runat="server" style="z-index: 1; position: absolute; top: 1085px; left: 215px; width: 570px;" Text="Juvenile birds have a less prominent grey nape, etc. Their eyes are a pale blue in the first year, turning to brown in the spring of their second year and eventually to light grey. Their call is a high-pitched metallic sounding kyow or tchack, after which it is named."></asp:Label>
        <asp:Label ID="lblMagpieDescript" runat="server" style="z-index: 1; position: absolute; top: 1265px; left: 35px; width: 595px;" Text="From a distance the Magpie is a black and white crow with a long tail. The tail accounts for over half the total length of the bird and is an indication of the bird's status in its society. Magpies are very vocal birds, but the harsh repeated chattering chacker chacker call of the Magpie is unmistakable."></asp:Label>
        <asp:Label ID="lblPheasantSpec" runat="server" style="z-index: 1; position: absolute; top: 1405px; left: 205px; width: 370px;" Text="Length: 75-90 cm  (30-36&quot) Wing Span: 80-90 cm  (32-36&quot) Weight: 900-1500 g  (2-3½lb) Present: All Year"></asp:Label>
        <asp:Label ID="lblPheasantDescript" runat="server" style="z-index: 1; position: absolute; top: 1460px; left: 205px; width: 580px;" Text="The Pheasant is a non-native bird that was first introduced by the Normans in the 11th century as a game bird. The song of the male is a far-carrying, harsh korr kok."></asp:Label>
        <asp:Label ID="lblPigeonSpec" runat="server" style="z-index: 1; position: absolute; top: 1585px; left: 255px; width: 365px; height: 20px" Text="Length: 31-34 cm  (12-13&quot) Wing Span: 63-70 cm  (25-28&quot) Weight: 230-370 g  (8-13 oz) Present: All Year"></asp:Label>
        <asp:Label ID="lblPigeonDescript" runat="server" style="z-index: 1; position: absolute; top: 1645px; left: 50px; width: 575px; height: 25px" Text="The Feral Pigeon is descended from the Rock Dove and can have similar plumage, though there are also many mixes of black, browns, white and piebald. The call is a continuous, bubbling moan. "></asp:Label>
        <asp:Label ID="lblRavenSpec" runat="server" style="z-index: 1; position: absolute; top: 1765px; left: 210px; width: 359px;" Text="Length: 64 cm (25&quot) Wing Span: 120-150 cm (47-59&quot) Weight: 0.8-1.5 kg (1¾-3¼ lb) Present: All Year"></asp:Label>
        <asp:Label ID="lblRavenDescript" runat="server" style="z-index: 1; position: absolute; top: 1825px; left: 210px; width: 614px;" Text="The Raven is our largest crow and is about the same size as a Buzzard or about half as big again as Carrion Crows and Rooks. The Raven's call is a very deep croaking, kronk kronk kronk, which once heard and identified will be easily remembered."></asp:Label>
        <asp:Label ID="lblRobinSpec" runat="server" style="z-index: 1; position: absolute; top: 1945px; left: 295px; width: 325px;" Text="Length: 13-14 cm  (5&quot) Wing Span: 20-22 cm  (8-9&quot) Weight: 16-22 g  (½-¾ oz) Present: All Year"></asp:Label>
        <asp:Label ID="lblRobinDescript" runat="server" style="z-index: 1; position: absolute; top: 2005px; left: 40px; width: 580px; height: 20px" Text="Robins are rarely seen or heard during midsummer (July-August) when they are moulting and become rather retiring. At other times they can usually be heard singing their melodious warbling song from strategic perches, often quite high up; it sounds like twiddle-oo, twiddle-eedee, twiddle-oo twiddle. In the winter, it can sound wistful, some say mournful, but around Christmastime the song becomes stronger and more passionate."></asp:Label>
        <asp:Label ID="lblRookSpec" runat="server" style="z-index: 1; position: absolute; top: 2165px; left: 225px; width: 329px;" Text="Length: 45 cm  (18&quot) Wing Span: 80-90 cm  (32-36&quot) Weight: 460-520 g  (1-1¼ lb) Present: All Year"></asp:Label>
        <asp:Label ID="lblRookDescript" runat="server" style="z-index: 1; position: absolute; top: 2225px; left: 220px; width: 570px;" Text="The Rook is about the same size as the Carrion Crow but is more untidy in its appearance. Rooks are rarely alone and so their raucous caws can become overwhelming."></asp:Label>
        <asp:Label ID="lblSwallowSpec" runat="server" style="z-index: 1; position: absolute; top: 2355px; left: 265px; width: 350px;" Text="Length: 17-20 cm  (7-8&quot) Wing Span: 30-35 cm  (12-14&quot) Weight: 16-25 g  (½-1 oz) Present: Summer"></asp:Label>
        <asp:Label ID="lblSwallowDescript" runat="server" style="z-index: 1; position: absolute; top: 2415px; left: 35px; width: 580px;" Text="Swallows have long wings and long tail streamers and are often found circling gracefully overhead or swooping low over water and ground. Their song is a rambling warble of trills and twitters sometimes sounding almost like a sparrow."></asp:Label>
        <asp:Label ID="lblFooter" runat="server" BackColor="White" style="z-index: 1; position: absolute; top: 2545px; left: 130px" Text="If you have recently spotted any of these birds why don't you submit them in the Bird Identifier!"></asp:Label>
    </p>
    <asp:Panel ID="Panel1" runat="server" BackColor="White" BorderColor="White" BorderStyle="Solid" BorderWidth="10px" style="z-index: 1; width: 760px; height: 125px; position: absolute; top: 100px; left: 25px">
        <div class="text-center">
            <h1>Gallery</h1>
            <h5>Welcome to the Gallery page where you can look at some the birds you may be able to spot in your gardens and in your surrounding area.</h5>
        </div>
    </asp:Panel>
</asp:Content>
