using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.UI;
using System.Web.UI.WebControls;
using System.Data.SqlClient;
using System.Data;
using System.Configuration;

namespace WebApplication1
{
    public partial class League_Table : System.Web.UI.Page
    {
        protected void Page_Load(object sender, EventArgs e)
        {
            lblUsername.Text = User.Identity.Name;
            GridView1.DataBind();
        }

        protected void Button1_Click(object sender, EventArgs e)
        {

            //Create variable to point to image upload folder 

            string image_folder = Server.MapPath("~\\uploadedimages\\");

            //Create 2 variables and set the file names to blank in case User does not upload any files - DB entries will still be made

            string dbfilename1 = "";
            string dbfilename2 = "";

            //Check if the Image Fileupload control has a file or not

            if (FileUpload1.HasFile)
            {

                //If the Fileupload control has a file, change the value of the variable to the selected image file name

                string filename1 = FileUpload1.FileName.ToString();

                //Copy the selected Image file from the Users device accross the Internet and save it into the Image folder within the Web App structure

                FileUpload1.SaveAs(image_folder + filename1);

                //Assign the new file name to the variable used to populate the DB - change from "" to actual file name

                dbfilename1 = filename1;

            }

            //Repeat as above for Multimedia Clip - audio or video

            string multimedia_folder = Server.MapPath("~\\uploaded_multimedia\\");

            if (FileUpload2.HasFile)
            {

                string filename2 = FileUpload2.FileName.ToString();

                FileUpload2.SaveAs(multimedia_folder + filename2);

                dbfilename2 = filename2;

            }

            //Create DB Connection - point to SQL 

            // create sql connection object. make sure to put a valid connection string


            string connectionString = (ConfigurationManager.ConnectionStrings["TACLConnectionString"].ConnectionString);
            //Then I would reference the string e.g

            SqlConnection conn = new SqlConnection(connectionString);


            SqlCommand cmd = new SqlCommand("Insert into LeagueTable3cs" + "(BirdName, Quantity, Place, Date, Image, MediaClip, Username, Size, Feathers, Beak, SchoolName)"
          + "Values(@1, @2, @3, @4, @5, @6, @7, @8, @9, @10, @11) Select SCOPE_IDENTITY()");



            using (SqlDataAdapter sda = new SqlDataAdapter())
            {
                //Define the structure of the SQL Statement - used to executed instructions against the DB Table 
                //    //The DB Table name and each field is indentified in the command.
                //    //INSERT commands includes Primary Key insertion - that is generated by the DB itself
                cmd.Parameters.AddWithValue("@1",  TextBox1.Text.ToString());
                cmd.Parameters.AddWithValue("@2",  TextBox2.Text.ToString());
                cmd.Parameters.AddWithValue("@3",  TextBox3.Text.ToString());
                cmd.Parameters.AddWithValue("@4",  DateTime.Now.ToString());
                cmd.Parameters.AddWithValue("@5",  dbfilename1.ToString());
                cmd.Parameters.AddWithValue("@6",  dbfilename2.ToString());
                cmd.Parameters.AddWithValue("@7",  User.Identity.Name);
                cmd.Parameters.AddWithValue("@8",  DropDownList1.ToString());
                cmd.Parameters.AddWithValue("@9",  DropDownList2.ToString());
                cmd.Parameters.AddWithValue("@10", DropDownList5.ToString());
                cmd.Parameters.AddWithValue("@11", TextBox11.Text.ToString());
                cmd.Connection = conn;


                //Added cmd.ExecuteNonQuery(); to execute the query to add the data to the database 
                conn.Open();
                cmd.ExecuteNonQuery();
                conn.Close();

                GridView1.DataBind();

            }
        }



        protected void DropDownList1_SelectedIndexChanged(object sender, EventArgs e)
		{

		}

        protected void btnReset_Click(object sender, EventArgs e)
        {
            TextBox1.Text = "";
            TextBox2.Text = "";
            TextBox3.Text = "";
            TextBox11.Text = "";

            DropDownList1.Text = "Please choose an option";
            DropDownList2.Text = "Please choose an option";
            DropDownList5.Text = "Please choose an option";

           
        }
    }
}